name: Run Unit Test and Upload Coverage Report

on:
  # Triggered whenever push to main 
  push:
    branches: [ "main" ]

  # Triggered whenever a pull request is created on main
  pull_request:
    branches: [ "main" ]
    types: [opened]

  # Allow manual trigger
  workflow_dispatch:

jobs:
  build-run-upload:
    # Create a container of the latest Ubuntu, other values could be
    # ubuntu-latest, ubuntu-22.04, etc.
    runs-on: ubuntu-22.04
    
    steps:
      # We want to use GitHub CI checkout version 3 to check out our branch
      - uses: actions/checkout@v3
      
      # Install some system pacakges
      - name: Install build packages
        run: |
          sudo apt update
          sudo apt install -y software-properties-common
          sudo apt-get install -y doxygen
          sudo apt install -y doxygen lcov gcovr
      - name: Install Doxygen
        run: |
          sudo apt-get update -q
          sudo apt-get install -y doxygen
      - name: Configure and Build
        run: |
          cmake -D WANT_COVERAGE=ON -D CMAKE_BUILD_TYPE=Debug -S ./ -B build/
          cmake --build build/
      - name: Run Tests and Generate Code Coverage
        run: |
          cd build/
          ctest --output-on-failure || true
      # Upload coverage result to CodeCov
      - name: Upload coverage result to CodeCov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          files: ${{github.workspace}}/build/test_coverage.info
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
     
      # Add a step to generate the Codecov badge status
      - name: Generate Codecov Badge Status
        run: |
          echo "Generating Codecov Badge Status..."
          # Example using curl:
          # curl -o codecov-badge.svg https://app.codecov.io/gh/Achuthankrishna/PID-TDD
          # Example using wget:
          # wget -O codecov-badge.svg https://app.codecov.io/gh/Achuthankrishna/PID-TDD
          echo "Codecov Badge Status generated successfully."

          
